# Generated by Django 4.1.5 on 2023-02-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_courseattachment_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
