# Generated by Django 4.1.5 on 2023-02-26 10:37

import course.api.models.course_attachment_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursefeedback_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursefeedback',
            name='unique_user_feedback_to_a_course',
        ),
        migrations.AlterField(
            model_name='courseattachment',
            name='name',
            field=models.FileField(upload_to=course.api.models.course_attachment_model.upload_to_directory),
        ),
        migrations.AddConstraint(
            model_name='coursefeedback',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_feedback_to_a_course', violation_error_message='A user can feedback once a coruse'),
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coursefeedback',
            table=None,
        ),
    ]
