# Generated by Django 4.1.5 on 2023-02-28 06:54

import course.api.models.course_video_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_coursefeedback_unique_user_feedback_to_a_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='name',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='file_name',
            field=models.FileField(default=None, upload_to=course.api.models.course_video_model.upload_to_directory),
            preserve_default=False,
        ),
    ]
