# Generated by Django 4.1.5 on 2023-02-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_coursevideo_name_coursevideo_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='course.course'),
        ),
    ]
