# Generated by Django 4.1.5 on 2023-02-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_coursepart_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattachment',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='course.coursepart'),
        ),
    ]
