# Generated by Django 4.1.5 on 2023-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='label',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
