# Generated by Django 4.1.5 on 2023-01-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=20
                    ),
                ),
                ("phone", models.IntegerField()),
                ("dob", models.DateField()),
                ("bio", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="instuctor/image")),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorIdCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_type", models.CharField(max_length=100)),
                ("passport_front", models.CharField(max_length=100)),
                ("passport_back", models.CharField(max_length=100)),
                ("id_front", models.CharField(max_length=100)),
                ("id_back", models.CharField(max_length=100)),
                (
                    "instructor_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instructor.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorExprience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                ("documentation", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "instructor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instructor.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                ("deploma", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "instructor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instructor.instructor",
                    ),
                ),
            ],
        ),
    ]
