# Generated by Django 4.1.5 on 2023-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="instuctor/image"),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
