# Generated by Django 4.1.5 on 2023-01-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0002_alter_instructor_dob_alter_instructor_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructoreducation",
            name="instructor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor",
                to="instructor.instructor",
            ),
        ),
    ]
