# Generated by Django 4.1.7 on 2023-02-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('documentation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='instructor.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='InstructorExprience',
        ),
    ]
