# Generated by Django 4.1.5 on 2023-01-31 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0003_alter_instructoreducation_instructor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructoreducation",
            name="instructor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Education",
                to="instructor.instructor",
            ),
        ),
    ]
