# Generated by Django 4.1.7 on 2023-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructorexperience_delete_instructorexprience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorexperience',
            name='documentation',
            field=models.ImageField(blank=True, null=True, upload_to='instructor/documents'),
        ),
    ]
