# Generated by Django 4.1.7 on 2023-02-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_alter_instructorexperience_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoridcart',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='instructor-id/back'),
        ),
        migrations.AlterField(
            model_name='instructoridcart',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='instructor-id/front'),
        ),
        migrations.AlterField(
            model_name='instructoridcart',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to='instructor-passport/back'),
        ),
        migrations.AlterField(
            model_name='instructoridcart',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to='instructor-passport/frant'),
        ),
    ]
