# Generated by Django 4.1.5 on 2023-01-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0005_alter_instructoreducation_deploma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorexprience",
            name="instructor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exprience",
                to="instructor.instructor",
            ),
        ),
    ]
