# Generated by Django 4.1.5 on 2023-01-29 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_province_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.province'),
        ),
    ]
